### ISSUE TITLE
ActiveDirectoryDsc: Rename module from xActiveDirectory

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ActiveDirectoryDsc#312]
Once community feels comfortable that this module follows the style guideline and test guidelines (minus the integration tests we can't enforce yet), then let's rename this module.

See issue https://github.com/PowerShell/xActiveDirectory/issues/172 that should be closed first before this one.

**Comment by johlju** [comment]
I gathered the issues that I think we need to resolve before we rename the module in this project board https://github.com/PowerShell/xActiveDirectory/projects/2. If you think more issues should be added, or an issue should not be a part of the board then feel free to comment. I don't think we should enforce to have the integration tests since there are no easy way of running them yet (still working on that).

We are very close to being able to rename the repo, just smaller issues.

**Comment by PlagueHO** [comment]
Nice! If I get time I'll pick some up.

**Comment by johlju** [comment]
Would be great, and the reason we are so close is because @X-Guardian has put so much work closing issues! 😃

**Comment by johlju** [comment]
This one is ready to be worked on!

**Comment by ChrisLGardner** [comment]
If I get some time tomorrow or this week then I'll look at getting this done. Shouldn't be too hard with a bit of regex.

**Comment by johlju** [comment]
The one that starts work on this, please let me know so I can assign it so others know not to start too :smile:

**Comment by timhaintz** [comment]
@ChrisLGardner let me know if you won’t get a chance. I should have some time tonight (Australia East time) to get started. Thanks.

**Comment by johlju** [comment]
@gaelcolas PR for this issue is ready to be merged soon (just minor tweaks), so can you please rename this repo when you have some time? Also we need the token from AppVeyor since previously when renaming a repo the AppVeyor token for status badges changes.

**Comment by gaelcolas** [comment]
Alright, the Repo has been renamed, let me know if you need anything else.

**Comment by johlju** [comment]
@gaelcolas It seems that AppVeyor did not understand the rename of the repo. I think we need to readd the repo to the AppVeyor "PowerShell account". 😕 @kwirkykat not sure if @gaelcolas have permission there, is this something you can help with?

**Comment by johlju** [comment]
This is a list from the rename of *SqlServerDsc*, the same need to be done here. *The list is from https://github.com/PowerShell/SqlServerDsc/pull/902#issuecomment-345773058*.

1. Rename repository to ActiveDirectoryDsc.
1. Connect AppVeyor if needed.
1. Connect CodeCov if needed. *This was not needed according to https://github.com/PowerShell/SqlServerDsc/issues/943#issuecomment-359148660*.
1. Close and reopen this PR to kick of the tests again.
1. Merge the PR into dev when tests passes.
1. Release the first version of ActiveDirectoryDsc.
1. After release, update xActiveDirectory on PowerShell Gallery saying that it is obsolete. *@kwirkykat fixed this for xSqlServer, see https://github.com/PowerShell/SqlServerDsc/issues/943#issuecomment-360216866*.

/cc @gaelcolas

**Comment by gaelcolas** [comment]
I should have access. It's tied with the repo's permission.

**Comment by johlju** [comment]
Cool! When you have time please add the ActiveDirectoryDsc repo 😊
