### ISSUE TITLE
ADObjectPermissionEntry: access denied when running under non domain administrator account

### ISSUE THREAD

**Issue by JoshuaJSwain** [dsccommunity/ActiveDirectoryDsc#314]
#### Details of the scenario you tried and the problem that is occurring
When running this resource under a least privileged account (not domain admin) the resource errors with access denied setting the ACL. The identity reference account has full control of the OU and can edit the ACL using the UI and other powershell methods. The bug appears to be in get-acl | set-acl.

#### Verbose logs showing the problem

```
audit failure logs on domain controller event 4662

Operation:
	Operation Type:		Object Access
	Accesses:		WRITE_DAC
				WRITE_OWNER
				ACCESS_SYS_SEC
				
	Access Mask:		0x10C0000
	Properties:		---
	{bf967aa5-0de6-11d0-a285-00aa003049e2}
```

#### Suggested solution to the issue
Change set resources to use adsi instead of get-acl , set-acl

```
$acl = [adsi]"LDAP://$path"

$modified = $false
$acl.PSBase.ObjectSecurity.ModifyAccessRule([System.Security.AccessControl.AccessControlModification]::Add,$ace,[ref]$modified)
$acl.PSBase.CommitChanges()
```

working example:

```powershell   
# Get the current acl
$acl = [adsi]"LDAP://$path"

if ($Ensure -eq 'Present')
{
    Write-Verbose "Add access rule to object $Path"
    $ntAccount = New-Object -TypeName 'System.Security.Principal.NTAccount' -ArgumentList $IdentityReference
    $ace = New-Object -TypeName 'System.DirectoryServices.ActiveDirectoryAccessRule' -ArgumentList $ntAccount, $ActiveDirectoryRights, $AccessControlType, $ObjectType, $ActiveDirectorySecurityInheritance, $InheritedObjectType

    $modified = $false
 $acl.PSBase.ObjectSecurity.ModifyAccessRule([System.Security.AccessControl.AccessControlModification]::Add,$ace,[ref]$modified)

    $acl.PSBase.CommitChanges()
}
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

```powershell   

Import-Module C:\temp\xActiveDirectory\DSCResources\MSFT_xADObjectPermissionEntry\MSFT_xADObjectPermissionEntry.psm1

$ensure = 'present'
$path = 'OU=Servers,DC=contoso,DC=com'
$identityreference = 'contoso\devbosqlwc999$'
$activedirectoryrights = @('createchild', 'deletechild')
$accesscontroltype = 'allow'
$objecttype = 'bf967a86-0de6-11d0-a285-00aa003049e2                          '
$activedirectorysecurityinheritance = 'all'
$inheritedobjecttype = '00000000-0000-0000-0000-000000000000'

Set-TargetResource -Ensure Present -Path $path -IdentityReference $identityreference -ActiveDirectoryRights $activedirectoryrights `
-AccessControlType Allow -ObjectType $objecttype -ActiveDirectorySecurityInheritance $activedirectorysecurityinheritance -InheritedObjectType $inheritedobjecttype -Verbose

"VERBOSE: Add access rule to object OU=Servers,DC=contoso,DC=com
Set-Acl : Access is denied
At C:\temp\xActiveDirectory\DSCResources\MSFT_xADObjectPermissionEntry\MSFT_xADObjectPermissionEntry.psm1:232 char:12
+     $acl | Set-Acl -Path "AD:$Path"
+            ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (OU=Servers,DC=contoso,DC=com:String) [Set-Acl], UnauthorizedAccessException
    + FullyQualifiedErrorId : ADProvider:SetSecurityDescriptor:AccessDenied,Microsoft.PowerShell.Commands.SetAclCommand"
```  

#### The operating system the target node is running

```
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19358.amd64fre.winblue_ltsb_escrow.190505-1600
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
```

#### Version and build of PowerShell the target node is running

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1005   
```

#### Version of the DSC module that was used ('dev' if using current dev branch)

2.26.0.0

**Comment by johlju** [comment]
Thanks for reporting this! I label this as a bug, and help wanted so that someone in the community can work on a fix.

**Comment by X-Guardian** [comment]
Hi @JoshuaJSwain, I'm taking a look at this issue, and trying to understand the problem. The only way you can execute the DscResource with a least privileged account as by using the `PsDscRunAsCredential` on the resource. 
The `IdentityReference` parameter on this resource is the account you want to give permissions to, not the account the DSC is running as.

I've tested this resource using `PsDscRunAsCredential` with a least privileged account remotely on a non-domain controller, and it is successful.

**Comment by X-Guardian** [comment]
I'm closing this issue for now. If you have any more information to add to this, please feel free to re-open it.

**Comment by J4yD4n** [comment]
I just came across this issue. It does still exist as a problem and it does keep permissions from applying unless you run as a DA. Can this issue be re-opened or should I open a new issue and reference this one? After this week I can work on some code to apply permissions without requiring DA.

**Comment by X-Guardian** [comment]
Please create a new issue @J4yD4n.
