### ISSUE TITLE
ActiveDirectoryDsc: Add notice to pull request template about wiki content

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ActiveDirectoryDsc#398]
I think we should add a notice to the pull request template saying that the wiki content is generate automatically from certain files (schema, resource README.md, and resource examples files) so that new contributors know that they do not need to manually update the wiki, and doing so could remove the manually added content in the next release update.

**Comment by johlju** [comment]
Also maybe a notice should be added to the first page of the Wiki? Maybe re-word this section

>_This wiki is currently updated manually by a maintainer (using automatically generated documentation by the CI pipeline), so there can be some delay before this wiki is updated for the latest release._

**Comment by X-Guardian** [comment]
Definitely. I didn't realize that the Wiki was open for anyone to edit. Is that by default?

**Comment by X-Guardian** [comment]
https://help.github.com/en/articles/changing-access-permissions-for-wikis

**Comment by johlju** [comment]
Yes, default it is open for everyone. I don't have admin rights so can't change the permission (just collaborator). But having it open is okay I think, if we just could help avoid changes to files that is generated automatically so no one makes edits in the wrong place. Every change is logged in the normal commit history, so it could be traced (and reverted if need be). But if we feel we should change the permission that is possible too.

**Comment by X-Guardian** [comment]
Does anyone get notified if the Wiki is updated?

**Comment by johlju** [comment]
No, there ate nog GitHub notifikations for that I think. :thinking: Probably need a function that clones the wiki repo and look at the commit history.

**Comment by X-Guardian** [comment]
I would recommend getting it set to collaborator update only then. Someone could change a page, and no one notices.

**Comment by johlju** [comment]
My thought was that hopefully the community notices, and if a change is made to a markdown file that is automatically generated, that change will be reverted as soon as the new markdown file is published (assuming we have this automated in the near future).

**Comment by johlju** [comment]
But if we have it fully automated then we could switch the permission :thinking:

**Comment by johlju** [comment]
@gaelcolas what are you thoughts here?

**Comment by 1800Zeta** [comment]
Obvious answer is to lock down the permissions, but in light of this, would you want the wording under the top section (thanks for submitting) or the Task List? Any objections to the below?

> Please note that the wiki content is automatically generated using the information contained within the schema, resource README.md, and resource examples files. Manual editing of the wiki should not be performed as changes can be overwritten following the next release update.

**Comment by X-Guardian** [comment]
Closing this as the Wiki is now only editable by dsccommunity team members.
