### ISSUE TITLE
ADUser: Should always return all properties from Get-TargetResource

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ActiveDirectoryDsc#488]
If a AD user is not found the Get-TargetResource function should return all properties, but those properties that cannot be retrieved should be set to `$null`. Properties that cannot be retrieved regardless if the user exist or not should be set to the same value as passed in the parameter.

**Comment by johlju** [comment]
This issue should also resolve that the unit test evaluates so that the properties are returned correctly. Also add these properties to the integration test.

**Comment by X-Guardian** [comment]
Not sure this is a good idea. This will cause a much larger LDAP query getting all AD user attributes even if they are not being used in the configuration. This is not the model that the `Get-AdUser` cmdlet follows.
