### ISSUE TITLE
Release Date?

### ISSUE THREAD

**Issue by davidwallis3101** [dsccommunity/ActiveDirectoryDsc#531]
When is the latest commit going to be pushed to the gallery?

Reluctant to package it and host internally and later cause issues if its imminent? (and there is functionality im interested in)

Thanks

**Comment by X-Guardian** [comment]
The repo needs converting to the new CI process first, and the method to do that is still being finalized. I would doubt this will be completed before Jan.

**Comment by johlju** [comment]
Getting closer and closer to be able to release SqlServerDsc, when that one is done it will go quicker doing this one and the rest of the modules. 😊

**Comment by johlju** [comment]
@X-Guardian is working on getting this to use the continuous delivery pipeline.

**Comment by X-Guardian** [comment]
Version 5.0.0 of ActiveDirectoryDsc has been released.
