### ISSUE TITLE
ADReplicationSite: No Credential Parameter

### ISSUE THREAD

**Issue by anorstrom** [dsccommunity/ActiveDirectoryDsc#613]
#### Details of the scenario you tried and the problem that is occurring
We want to use the ActiveDirectoryDsc module to manage our AD Sites. However, the AD Site resources does not support the Credential parameter, so we cannot use it in our production since we need to run with a certain credential in our environment. 

The resources we want to use:
ADReplicationSite
ADReplicationSubnet
ADReplicationSiteLink

#### Verbose logs showing the problem
N/A

#### Suggested solution to the issue
Add the Credential parameter to the AD Site resources in the same way as it has been added to for example to the ADGroup resource 

https://github.com/dsccommunity/ActiveDirectoryDsc/blob/fa3aee9c066823d58c97b9e361233289a974883a/source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1#L38

https://github.com/dsccommunity/ActiveDirectoryDsc/blob/fa3aee9c066823d58c97b9e361233289a974883a/source/DSCResources/MSFT_ADGroup/MSFT_ADGroup.psm1#L111

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
N/A
```

#### The operating system the target node is running
Windows Server 2016

#### Version and build of PowerShell the target node is running
N/A

#### Version of the DSC module that was used
6.0.1

**Comment by X-Guardian** [comment]
Hi @anorstrom, as long as the device that you are executing the DSC on is domain connected and is running PowerShell 5 or above, you can use the automatic `PSDscRunAsCredential` property to specify your desired domain credentials for each resource. See [Use Credentials with DSC Resource](https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/runasuser?view=powershell-5.1) for further info.

**Comment by anorstrom** [comment]
Thank you @X-Guardian   
I tested and it seems to work 👍
