### ISSUE TITLE
ADGroup: Proposal to Support Group Members Across One-Way External Trusts 

### ISSUE THREAD

**Issue by X-Guardian** [dsccommunity/ActiveDirectoryDsc#619]
#### Details of the scenario you tried and the problem that is occurring

The current `ADGroup` resource does not support `Getting` or `Setting` an AD group that contains foreign security principals that are members from one way trusted domains.

Issue #616 discusses this with regard to `Getting` an AD group in this scenario, and PR #617 resolves this. We now need to develop a solution for `Setting` an AD group with a member from a one way trusted domain.

We were unable to return the remote `DN` of the member, so what is returned for the different `MembershipAttributes` is as follows:

| MembershipAttribute | Value | Example
|-|-|-
| SamAccountName | Domain Qualified SamAccountName | ADATUM/user1
| SID | SID | S-1-5-21-673788509-2975267852-3991298411-1183
| DistinguishedName |  ForeignSecurityPrincipalDN | CN=S-1-5-21-673788509-2975267852-3991298411-1183,CN=ForeignSecurityPrincipals,DC=contoso,DC=com
| ObjectGUID | ForeignSecurityPrincipal GUID | df3f5cb1-752e-42be-9570-f9c4b261ac0a

The most useful one for normal usage is the domain qualified SamAccountName, so an AD Group resource would look like this:

```powershell
ADGroup 'dl1'
{
    GroupName  = 'DL_APP_1'
    GroupScope = 'DomainLocal'
    Members    = @(
        'John'
        'Jim'
        'ADATUM\Fred'
    )
}
```

In my testing, the only way I could add a foreign security principal member to a group was to use the `Set-ADGroup` cmdlet specifying the user `DN` as a member in the `-Add` property. Sample code to achieve this follows:

```powershell
$samAccountName = 'CONTOSO\DscTestUser'
$groupName = 'test-domainlocal-group'

if ($samAccountName -like '*\*')
{
    $domain = $samAccountName.Split('\')[0]
    $accountName = $samAccountName.Split('\')[1]
    
    $ntAccount = New-Object System.Security.Principal.NTAccount($domain, $accountName)
    $sid = $ntAccount.Translate([System.Security.Principal.SecurityIdentifier])
    
    $adObject = Get-ADObject -Filter "objectSid -eq  '$($sid.value)'"
    Set-ADGroup -Identity $groupName -Add @{ member = $adobject.DistinguishedName } 
}
```

@jeremyciak and @davidwallis3101, can you check this makes sense, and test if possible on your domains, before we start working on a PR to implement this in the `ADGroup` resource.

**Comment by jeremyciak** [comment]
One clarification in your table where you reference the **SamAccountName** and **DistinguishedName** for the foreign security principal is that if we are working in *contoso.com* and the foreign security principal is from *adatum.com* then you would want the **DistinguishedName** to represent that `ForeignSecurityPrincipals` container in Active Directory from *contoso.com* as you have done, but the **Domain Qualified SamAccountName** would indicate the *adatum.com* so `adatum\user1` would be more representative.

> MembershipAttribute | Value | Example
> ------------ | ------------- | -------------
> SamAccountName | Domain Qualified SamAccountName | contoso/user1
> SID | SID | S-1-5-21-673788509-2975267852-3991298411-1183
> DistinguishedName | ForeignSecurityPrincipalDN | CN=S-1-5-21-673788509-2975267852-3991298411-1183,CN=ForeignSecurityPrincipals,DC=contoso,DC=com
> ObjectGUID | ForeignSecurityPrincipal GUID | df3f5cb1-752e-42be-9570-f9c4b261ac0a

**Comment by X-Guardian** [comment]
Yep good point, updated.

**Comment by jeremyciak** [comment]
Here is my attempt at a starting point similar to what you have offered... this is just to translate whatever `Members` values into a  `DistinguishedName` for standard processing from there:

```powershell
$Members = @(
    'John'
    'Jim'
    'ADATUM\Fred'
)
$MembershipAttribute = 'SamAccountName'

$memberDistinguishedNames = [System.Collections.ArrayList]::new()

if ($MembershipAttribute -eq 'SamAccountName')
{
    if (($Members -match '\\').Count -gt 0)
    {
        $foreignSecurityPrincipals = Get-ADObject -Filter "ObjectClass -eq 'ForeignSecurityPrincipal'" -Properties ObjectSid
        
        $Members | Where-Object -FilterScript { $_ -match '\\' } | ForEach-Object -Process {
            $samAccountName = $_
            
            $distinguishedName = $foreignSecurityPrincipals | Where-Object -FilterScript {
                $samAccountName -eq [System.Security.Principal.SecurityIdentifier]::new($_.ObjectSid).Translate([System.Security.Principal.NTAccount]).Value
            }
            $memberDistinguishedNames.Add($distinguishedName)
        }
    }
    else
    {
        $Members | ForEach-Object -Process {
            $distinguishedName = (Get-ADObject -Filter "SamAccountName -eq '$($_)'").DistinguishedName
            $memberDistinguishedNames.Add($distinguishedName)
        }
    }
}
else
{
    # Do stuff for the other MembershipAttribute options
}
```

**Comment by davidwallis3101** [comment]
Embarrassingly my test env built with automated labs - I left a pretty generic pwd on and the boxes somehow got compromised.. SO I blew it all away... They've now added a feature to allow locking the NSG down to an IP during config which should help a bit.. So I'll re-provision this shortly and test.

I'm interested in the method you found for adding foreign security principals though as I didn't manage to find anyway that worked other than the code I previously posted.

I've also not managed to add the foreign security principals without permissions in the target domain. Can you confirm what permissions your account running this as has in each domain?

**Comment by X-Guardian** [comment]
Hi @davidwallis3101,  I thought it was too easy. The code I posted only works if there is already a `ForeignSecurityPrincipal` reference for the user. I just tested creating a brand new user in the trusted domain and I can resolve the SID from the trusting domain, but I need the `DistinguishedName` for `Set-ADGroup` which I don't have because there is no FSP yet :(
If this needs credentials for the other domain to create the FSP then I don't know how we can effectively implement this, as there may be many trusted domains.

**Comment by jeremyciak** [comment]
Alright, I think I have something that works now after referencing what @davidwallis3101 did with his code. Utilizing the SID value instead of the `DistinguishedName` is the key. Here is a function to resolve the SID for whatever `MembershipAttribute`:
```powershell
function Resolve-MembersSecurityIdentifier {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, ValueFromPipeline = $true, ValueFromPipelineByPropertyName = $true)]
        [System.String[]]
        $Members,

        [Parameter()]
        [ValidateSet('SamAccountName', 'DistinguishedName', 'SID', 'ObjectGUID')]
        [System.String]
        $MembershipAttribute = 'SamAccountName'
    )

    begin
    {
        # This regular expression looks for the following:
        #   - Begins with: 'CN=S-1-5-21'
        #   - Next comes 3 sections of a dash followed by 10 digits: '-1234567890-1234567890-1234567890'
        #   - Followed by another dash and any number of digits: '-1234'
        #   - Next is: ',CN=ForeignSecurityPrincipals'
        #   - And last is at least 2 sections of a comma followed by 'DC=' and the fully qualified AD domain segments: ',DC=contoso,DC=com'
        # e.g. - 'CN=S-1-5-21-1234567890-1234567890-1234567890-1234,CN=ForeignSecurityPrincipals,DC=contoso,DC=com
        $foreignSecurityPrincipalDistinguishedNameRegex = '^CN[=]S[-]1[-]5[-]21([-][0-9]{10}){3}[-][0-9]+[,]CN[=]ForeignSecurityPrincipals([,]DC[=][\w-]+){2,}$'

        $property = switch ($MembershipAttribute)
        {
            'SID'
            {
                'ObjectSID'
            }

            default
            {
                $MembershipAttribute
            }
        }
    }

    process
    {
        if ($MembershipAttribute -eq 'SID')
        {
            return $Members
        }

        $Members | ForEach-Object -Process {
            try
            {
                if ($MembershipAttribute -eq 'SamAccountName' -and $_ -match '\\')
                {
                    $samAccountNameSplit = $_ -split '\\'
                    $domain = $samAccountNameSplit[0]
                    $accountName = $samAccountNameSplit[1]
                    [System.Security.Principal.NTAccount]::new($domain, $accountName).Translate([System.Security.Principal.SecurityIdentifier]).Value
                }
                elseif ($MembershipAttribute -eq 'DistinguishedName' -and $_ -match $foreignSecurityPrincipalDistinguishedNameRegex)
                {
                    ($_ -replace '^CN[=]' -split ',')[0]
                }
                else
                {
                    (Get-ADObject -Filter "$($property) -eq '$($_)'" -Properties ObjectSID, SamAccountName).ObjectSID
                }
            }
            catch
            {
                Write-Warning -Message "Unable to resolve Security Identifier for $($MembershipAttribute) '$($_)'"
            }
        }
    }
}
```

With this function you can then reference various use cases, however the one that I think makes for the easiest testing is this:

- Assume you have two groups created: `Group A` and `Group B`
- Place whatever mixture of members you want in `Group A`
- Run the below code snippet to take those members and add them to `Group B`

```powershell
(Get-ADGroup -Identity 'Group A' -Properties Members).Members |
    Resolve-MembersSecurityIdentifier -MembershipAttribute 'DistinguishedName' |
    ForEach-Object -Process {
        Set-ADGroup -Identity 'Group B' -Add @{ member = "<SID=$($_)>" }
    }
```

The other option for testing would be similar to what @X-Guardian laid out previously:

```powershell
$Members    = @(
    'John'
    'Jim'
    'ADATUM\Fred'
)

$Members |
    Resolve-MembersSecurityIdentifier -MembershipAttribute 'SamAccountName' |
    ForEach-Object -Process {
        Set-ADGroup -Identity 'Group B' -Add @{ member = "<SID=$($_)>" }
    }
```

Please let me know your thoughts!

**Comment by X-Guardian** [comment]
Yep, but that doesn't help with the initial challenge: Create a brand new user in the trusted domain, and then try and add it to a group in the trusting domain without having any credentials for the trusted domain. I don't think it can be done.

**Comment by jeremyciak** [comment]
@X-Guardian, I just did exactly that and it worked. The secret is the reference to the Security Identifier instead of the `DistinguishedName`. Seriously, try my code snippets for yourself.

**Comment by jeremyciak** [comment]
Also potentially worth noting that by performing the group member addition based on the Security Identifier of the Foreign Security Principal it will automatically create that object in the Active Directory domain. This effort may foray into another DSC resource or something to help manage orphaned FSP objects over time.

**Comment by X-Guardian** [comment]
OK yes, you are right @jeremyciak. well done! I created another brand new user and specifying the SID for the `Set-ADGroup` `-Add` `Member` property works. I can see the FSP gets created, and no credentials are needed for the trusted domain.

This code snippet demonstrates it:
```powershell
$samAccountName = 'CONTOSO\DscTestUser4'
$groupName = 'test-domainlocal-group'

$ntAccount = New-Object System.Security.Principal.NTAccount($samAccountName)
$sid = $ntAccount.Translate([System.Security.Principal.SecurityIdentifier])

Set-ADGroup -Identity $groupName -Add @{ member = "<SID=$($sid.value)>" } 
```

**Comment by jeremyciak** [comment]
@X-Guardian, so what is the next step here? Should I start building out a PR?

**Comment by jeremyciak** [comment]
I have gone ahead and started efforts on this in my fork under the `develop` branch. I will open a PR once I have something functional.

**Comment by X-Guardian** [comment]
OK @jeremyciak, cheers.

**Comment by jeremyciak** [comment]
Alright @X-Guardian  and @davidwallis3101, [the PR](https://github.com/dsccommunity/ActiveDirectoryDsc/pull/620) is out there. Please go check it out and provide some feedback. Thanks!

**Comment by X-Guardian** [comment]
@jeremyciak and @davidwallis3101, ActiveDirectoryDsc Module version [6.1.0-preview006](https://www.powershellgallery.com/packages/ActiveDirectoryDsc/6.1.0-preview0006) has been released which includes this change. Can you download and test before I release v6.1.0 officially?
