### ISSUE TITLE
Expected requirements for contribution should be included in VSCode settings to make it easier

### ISSUE THREAD

**Issue by jeremyciak** [dsccommunity/ActiveDirectoryDsc#622]
Requirements like line length and other similar settings that can be added to the `settings.json` file under the `.vscode` folder should be so that contributors automatically benefit from those settings.

**Comment by jeremyciak** [comment]
```json
"files.defaultLanguage": "powershell",
"[powershell]": {
  "editor.rulers": [ 120 ]
},
"[markdown]": {
  "editor.rulers": [ 120 ]
}
```

**Comment by johlju** [comment]
We could also add a [`extensions.json`](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) that suggest adding the extension [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) that is used for validating markdown in HQRM tests.

**Comment by dan-hughes** [comment]
@johlju, I can pick this up.

Looking at the style guide is the line limit 120 or 80 chars?

Also is there anything else that needs adding as this is pretty old...

**Comment by johlju** [comment]
The style guidelines can be found at dsccommunity.org. We removed the hard line length limit a while back. We today also have a `dsccommunity` Plaster template in the Sampler project that have most of these settings already I think 🤔 This repo should have gotten those settings when the template was used on this template. 

Maybe this issue could just be closed if it already fixed?

**Comment by dan-hughes** [comment]
Looks like it matches. The only thing that might be beneficial is any recommended extensions? e.g.

- VScode Powershell
- Markdown Lint
- YAML
- CSpell (maybe?)

**Comment by johlju** [comment]
That sounds good. In SqlServerDsc these are used. YAML could be a good addition.

The Pester Test Adapter in the link below is a test I did in SqlServerDsc as it requires Pester 5 tests and specific settings, so that should not be a default in other repos until that extension becomes more stable I think 🤔

https://github.com/dsccommunity/SqlServerDsc/blob/main/.vscode/extensions.json

**Comment by dan-hughes** [comment]
Shall I also add into the Sampler template?
