### ISSUE TITLE
Migrating from Windows SBS 11 to Windows server 2016 - error in Active Directory

### ISSUE THREAD

**Issue by srikanth1997-in** [dsccommunity/ActiveDirectoryDsc#625]
Hi, I m trying to migrate the Windows SBS 11 to Windows server 2016 while in migration process, i am trying to install "Install-ADDSDomainController " in Power Shell, but I am Getting the below error....

Install-ADDSDomainController : Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGC' was not recognized.
At line:1 char:1

    Install-ADDSDomainController -NoGlobalCatalog:$false -CreateDnsDelega ...

      + CategoryInfo          : NotSpecified: (:) [Install-ADDSDomainController], TestFailedException
      + FullyQualifiedErrorId : Test.VerifyDcPromoCore.DCPromo.General.77,Microsoft.DirectoryServices.Deployment.PowerShell.Commands.InstallADDSDomainControllerCommand

Message Context RebootRequired Status

Verification of prerequisites for Domain Controller promotion failed. The specified argument 'ConfirmGC' was not recognized... Test.VerifyDcPromoCore.DCPromo.General.77 False Error

Please suggest the solution for the above..............

**Comment by johlju** [comment]
This repository is for a DSC resource that is used together with Desired State Configuration, I sounds to me like you are not using DSC or functionality in the DSC resource at all. If so I suggest you talk to Microsoft Support. If I misunderstood you, then please provide more information about your issue, how you use the DSC resource.

**Comment by X-Guardian** [comment]
Closing as not a DSC issue.
