### ISSUE TITLE
Some resources not compatible with Server 2008 R2

### ISSUE THREAD

**Issue by corydwood** [dsccommunity/ActiveDirectoryDsc#63]
I've modified a few of the **xActiveDirectory** resources to be compatible with Server 2008 R2 (such as **xADDomain**, **xADDomainController** and **xWaitForADDomain**) for use at my company.

I'd like to contribute these to GitHub, but I'm not sure where they should be placed. Should they be placed in a seperate **Pre2012ActiveDirectory** module or something similar?

**Comment by HemantMahawar** [comment]
@corydwood  Is there a reason to not update the existing version of **xActiveDirectory** module? IMHO, you should update the existing resources.

**Comment by corydwood** [comment]
@HemantMahawar One example would be the **xADDomainController** resource. In order to use this resource to build 2008 R2 DCs, I had to replace **Install-ADDSDomainController** with **dcpromo.exe**, which isn't compatible with 2012.

Another example is xWaitForADDomain. I had to replace **Get-ADDomain -Identity $DomainName -Credential $DomainUserCredential** with **New-Object DirectoryServices.DirectoryEntry("LDAP://$DomainName",$DomainUserCredential.UserName,$DomainUserCredential.GetNetworkCredential().Password)** in order to add a new DC to a domain containing only 2003 DCs.

This has been tested and works on all DCs 2003 and up, but it's not as clean as **Get-ADDomain**.

**Comment by iainbrighton** [comment]
I'm in the process of rewriting xADDomain to correct the authentication errors and logging. Bringing in 2008R2 support might be worth the effort, however, I don't think we need to worry about creating a new AD domain on anything old than 2008R2?

I don't like xWaitForADDomain's reliance on the AD cmdlets as it doesn't work on client OSes. Bringing in your changes in here would definitely make sense.

As for xADDomainController, should we just be targeting 2008R2 and onwards too? If it works downlevel then I guess it would be a bonus?

**Comment by corydwood** [comment]
The xWaitForADDomain change is pretty small, so I'll create a PR for that.

I'm less concerned with creating new domains older than 2012. I'm more concerned with adding new 2008 R2 DCs to an existing domain/forest, which requires dcpromo.

Would it make sense to update the existing xADDomainController resource to add an OS check so that it uses dcpromo for 2008 and 2008 R2, and Install-ADDSDomainController for 2012 and higher?

**Comment by HemantMahawar** [comment]
@corydwood @iainbrighton @TravisEz13 @KarolKaczmarek  Yes, an if/else based on OS version would be appropriate to address scenarios where cmdlets don't exist. This will ensure, over time, that the resource code layers on top of cmdlets only (when older version of OS are non-existent or not supported)

**Comment by GoateePFE** [comment]
I agree with Hemant's latest comment. If/else would be appropriate based on OS.

**Comment by iainbrighton** [comment]
I'd say that's a good place to start! We can look at merging in the other changes into xADDomain later if necessary?

**Comment by TravisEz13** [comment]
I agree with @HemantMahawar 's last comment.

**Comment by rdbartram** [comment]
I have a series of helper functions that I wrote for just this scenario among others like creating sites and subnets etc. Would it not make more sense the generalise the resource to one command and then load the separate helper module based on the OS Version. I can make a pull request to add the 2k8r2 helper psm1. Thoughts?

**Comment by johlju** [comment]
It looks like this work never started? It has so long now,  is someone still interested in adding 2008 R2 support?

**Comment by rdbartram** [comment]
For me it's not necessary, but I still have my helper functions if they're still needed

**Comment by johlju** [comment]
@rdbartram if you don't have use for it in these resource, then if you like you could publish them in a public GitHub Gist together with a MIT license, then someone could use them if they see a use for them.  🙂

**Comment by johlju** [comment]
Let's keep this issue open at least until [extended support ends](https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%20Server%202008%20R2%20Service%20Pack%201).

**Comment by X-Guardian** [comment]
Extended support for Server 2008 R2 has now ended so I am closing this issue.
