### ISSUE TITLE
"Read" attribute on resources. Needs some examples

### ISSUE THREAD

**Issue by SergeDubovsky** [dsccommunity/ActiveDirectoryDsc#662]
Namely, the ADGroup resource. As I understand, this:
DistinguishedName | Read | String | Returns the distinguished name of the Active Directory group

Is supposed to return the DN of created group. I have no idea how to read the output from DSC resources, if that even possible. Or, how to use this output in the parameter of other resource, such as ADManagedServiceAccount ManagedPasswordPrincipals, for example.

Thank you.

**Comment by johlju** [comment]
The read-only parameters cannot be used as an input to other resources in a compiled configuration. You can get read-only properties by calling `Get-DscConfiguration` or `Invoke-DscResource` using the method `Get`.
