### ISSUE TITLE
Azure Pipeline VM Image

### ISSUE THREAD

**Issue by matt2005** [dsccommunity/ActiveDirectoryDsc#667]
Azure Pipeline is set to use Ubuntu16.04 which no longer exists.

**Comment by gaelcolas** [comment]
ah, I was saying I need to bring this up to next DSC Community call.
Here's how I fixed it: https://github.com/gaelcolas/Sampler.GitHubTasks/pull/20

The issue we had with some newer versions was gitversion task failing, installing like this using dotnet tool install allows to work around the problem.
Make sure to update the variable value for ModuleVersion from `$(gitversion.NugetVersionV2)` to `$(NugetVersionV2)`...
Hit me up on slack if any question.

**Comment by matt2005** [comment]
I've updated it to 18.04 which is the LTS release. 
This is the minimum required change to fix the pipeline. 

I've not used the "latest" tag as that is not good practice for pipelines due to repeatability of the pipeline.
I'm sure you experienced issues due to using the "latest" tag as that is currently using 20.04 which may bring other issues with it as you have seen.
