### ISSUE TITLE
ADOrganizationalUnit - Recursive parameter is missing

### ISSUE THREAD

**Issue by powertim** [dsccommunity/ActiveDirectoryDsc#676]
Hi,

It would be great to be able to delete all child objects of an OU with a boolean parameter with name like "Recursive" as it's an option of the Powershell cmdlet Remove-ADOrganizationalUnit.

Thanks for your help !

**Comment by johlju** [comment]
From one point of view that would be great, but in another point of view it could result in a state that is not desired. I think it could potentially result in a configuration that both adds a child OU and the same configuration recursively deletes its parent OU. 🤔
